root: ./

redirects:
  help: README.md
  yo: README.md
  00-sup.html: page-1.md
  n00-00.html: page-2.md
  00-00.html: page-2.md
  sup: page-1.md
  ro.html: page-1.md
  00.html: page-2.md
  00-hi.html: page-1.md
  00-10.html: page-1.md
  01-i.html: page-1.md
  11-i.html: page-1.md
  00-node.html: page-1.md
  intro.html: README.md
  00-node.html: page-2.md
  00-00-setup.html: page-2.md
  00-01-upgrading.html: page-2.md
  00-02-validating.html: page-2.md
  00-03-bitcoin-relayer.html: page-2.md
  00-04-bitcoin-signer.html: page-2.md
  00-05-ibc-relayer.html: page-2.md
  

  
  
  
