root: ./

redirects:
  help: README.md
  yo: README.md
  00-sup.html: page-1.md
  n00-00.html: page-2.md
  00-00.html: page-2.md
  sup: page-1.md
  ro.html: page-1.md
  00.html: page-2.md
  00-hi.html: page-1.md
  00-10.html: page-1.md
  01-i.html: page-1.md
  11-i.html: page-1.md
  00-node.html: page-1.md
  

  
  
  
